name: 'PHP Unit Test'
description: 'PHP Unit Test'

inputs:
  mysql:
    description: 'Install mysql'
    required: false
    default: 'yes'

  postgres:
    description: 'Install postgres'
    required: false
    default: 'no'

  redis:
    description: 'Install Redis'
    required: false
    default: 'yes'

  clickhouse:
    description: 'Install Clickhouse'
    required: false
    default: 'yes'

  mysql-version:
    description: 'MySQL Image'
    required: false
    default: '8.0'

  postgres-version:
    description: 'Postgres Image'
    required: false
    default: '14.5'

  php-version:
    description: 'PHP Version'
    required: true
    default: '7.4'

  extensions:
    description: 'Extensions PHP'
    required: true
    default: 'bcmath, iconv, ctype, gd, mbstring, mysqli, pdo, pdo_mysql, sockets, zip, soap, intl, fileinfo, json, libxml, openssl, pcntl, posix, simplexml, zend-opcache, runkit7, igbinary, redis'

  config-file:
    description: 'Path to phpunit.xml'
    required: true
    default: 'phpunit.xml.dist'

  additional-parameters:
    description: 'Additional parameters for the phpunit command'
    required: true
    default: ''

  use-repository-config:
    description: 'To use or not the config from the repository'
    required: true
    default: 'yes'

  app-local-php:
    description: 'Config file'
    required: false
    default: ''

  post-install-cmd:
    description: 'Composer Post Install CMD'
    required: false
    default: 'yes'

  config-dir:
    description: 'Config directory for app-local.php'
    required: false
    default: 'config'

  migrate-command:
    description: 'Migrate command'
    required: false
    default: 'vendor/bin/phinx'

  npm-packages:
    description: 'NPM Packages'
    requierd: false
    default: ''

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - name: Install Node Packages
      if: ${{ inputs.npm-packages != '' }}
      run: npm install -g ${{ inputs.npm-packages }}
      shell: bash

    - name: Setup config
      if: ${{ (inputs.use-repository-config == 'yes') }}
      run: mv ./${{ inputs.config-dir }}/app_local_ci.php ./${{ inputs.config-dir }}/app_local.php
      shell: bash

    - name: Setup secret config
      if: ${{ (inputs.use-repository-config == 'no') && (inputs.app-local-php != 'no') }}
      run: echo "${{ inputs.app-local-php }}" > ./${{ inputs.config-dir }}/app_local.php
      shell: bash

    - name: Install Clickhouse
      if: ${{ inputs.clickhouse == 'yes' }}
      uses: EpicStep/clickhouse-github-action@v1.0.0

    - name: Install mysql
      if: ${{ inputs.mysql == 'yes' }}
      run: |
        docker run -itd --name eggheads -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=cakephp -p 3306:3306 mysql:${{ inputs.mysql-version }}
        sleep 10
      shell: bash

    - name: Install postgres
      if: ${{ inputs.postgres == 'yes' }}
      run: |
        docker run -itd --name pgsql_eggheads -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=postgres_cakephp -p 5432:5432 postgres:${{ inputs.postgres-version }}
        sleep 10
      shell: bash

    - name: Setup cache environment
      id: extcache
      uses: shivammathur/cache-extensions@v1
      with:
        php-version: ${{ inputs.php-version }}
        extensions: ${{ inputs.extensions }}
        key: eggheads-extension-php

    - name: Cache extensions
      uses: actions/cache@v2
      with:
        path: ${{ steps.extcache.outputs.dir }}
        key: ${{ steps.extcache.outputs.key }}
        restore-keys: ${{ steps.extcache.outputs.key }}

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        extensions: ${{ inputs.extensions }}
        tools: composer

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --no-progress --prefer-dist --optimize-autoloader
      shell: bash

    - name: Post Install dependencies
      if: ${{ inputs.post-install-cmd == 'yes' }}
      run: composer run-script post-install-cmd --no-interaction
      shell: bash

    - name: Create database mysql
      if: ${{ inputs.mysql == 'yes' }}
      run: mysql -h"127.0.0.1" -P"3306" -uroot -proot -e "CREATE DATABASE cakephp_test;"
      shell: bash

    - name: Create database postgres
      if: ${{ inputs.postgres == 'yes' }}
      run: PGPASSWORD=postgres psql -U postgres -e "CREATE DATABASE postgres_cakephp_test;"
      shell: bash

    - name: Migrations
      if: ${{ (inputs.mysql == 'yes') && (inputs.migrate-command != 'no') }}
      run: |
        ${{ inputs.migrate-command }} migrate 2> /dev/null && echo 'skip'
        ${{ inputs.migrate-command }} migrate
      shell: bash

    - name: PHPUnit
      run: php -dxdebug.mode=develop vendor/bin/phpunit --printer mheap\\GithubActionsReporter\\Printer --colors=always -c ${{ inputs.config-file }} ${{ inputs.additional-parameters }}
      shell: bash

    - name: delete mysql
      if: always()
      run: |
        docker rm -f eggheads
        docker volume rm $(docker volume ls -q --filter dangling=true)
      shell: bash